### ISSUE TITLE
ROR group project (Recipe App): Kanban board set up

### ISSUE THREAD

**Issue by karlavdelgadof** [karlavdelgadof/Recipe-app#14]
# ROR group project: Recipe App (Kanban board set up) :man_cook: :cut_of_meat: :apple:  :busts_in_silhouette: 

### Here you can find the link to our kanban board :arrow_down: 
[Our board](https://github.com/karlavdelgadof/Recipe-app/projects/1)

### This is our team :people_holding_hands: :technologist: 

@karlavdelgadof 

**[Optional included]:**
MEMBER 3

**Comment by prolajumokeoni** [comment]
Hi @karlavdelgadof kindly add a screenshot of the unpairing message you got from Student Success to work solo 👍🏿

**Comment by prolajumokeoni** [comment]
Hi @karlavdelgadof 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not show yet  you got approval to work solo, Kindly add a screenshot of the message you got from Student Success
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Davidosky007** [comment]
Hi @karlavdelgadof 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* All information about project provided 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by karlavdelgadof** [comment]
@prolajumokeoni Thank you, below I'm attaching a screenshot of the email received from Student Success :+1: 
![image](https://user-images.githubusercontent.com/92395484/202303707-bb328618-b7c1-458b-b003-3f642ca5f3e7.png)
